### ISSUE TITLE
Cutout offset for weighted mean modifies actual image

### ISSUE THREAD

**Issue by aswheaton** [aswheaton/fits-reducer#6]
The cutout offset used to prevent errors associated with negative count values appears to modify the data in the actual image, as visible in the RGB composite:

![rgb](https://user-images.githubusercontent.com/34541330/73563187-a8e8eb80-4454-11ea-8f44-bf5957c313ca.png)

This seems like an issue of scope, or possibly pointers. The offset of the cutout added in a6290dc0362922bdedd4fb6ce7612f46f1c09102 seems to modify the original image, not just the slice passed to `weighted_mean_2D()`, suggesting that `cutout` is actually a pointer to a slice of the FITS `.data` attribute.

Also visible in images exported from SAO DS9:
![m52_r_stacked_3](https://user-images.githubusercontent.com/34541330/73572523-e8b9ce00-4468-11ea-8871-f55996b1769e.jpeg)
![m52_g_stacked_3](https://user-images.githubusercontent.com/34541330/73572530-efe0dc00-4468-11ea-8056-aaf4cd659e8a.jpeg)

**Comment by SlothInABox** [comment]
I think we solved this by making cutout a new numpy array, not just a pointer.
Can you double check to make sure it is truly fixed?
